language: php
 
php:
  - 5.3
  - 5.4

env:
  global:
    - REPO_NAME=UserPermissions
    - PLUGIN_NAME=UserPermissions
    - DB=mysql
  matrix:
    - DB=mysql CAKE_VERSION=master
    - DB=mysql CAKE_VERSION=2.6
 
before_script:
  - git clone git://github.com/AlessandroMinoccheri/UserPermissions ../cakephp && cd ../cakephp
  - mv ../asset_compress plugins/AssetCompress
  - chmod -R 777 ../cakephp/app/tmp
 
script:
  - ./lib/Cake/Console/cake test AssetCompress AllTests --stderr